# Fuel Data Platform - Step 1: Inspect and Convert Raw Data Sources

This notebook performs step-by-step inspection of all raw data sources and converts Excel files to CSV format.

# Step 1: Inspect Source 1 - Global Crude Oil Prices

In [ ]:
import pandas as pd

# Load and inspect source1_global.csv
df_global = pd.read_csv("../data/raw/source1_global.csv")
print("Source 1 Global - Shape:", df_global.shape)
print("Columns:", df_global.columns.tolist())
print("Sample data:")
df_global.head()

Source 1 Global - Shape: (675, 2)
Columns: ['Date', 'Crude_Oil_Price']
Sample data:

         Date  Crude_Oil_Price
0  1970-01-01             1.21
1  1970-02-01             1.21
2  1970-03-01             1.21
3  1970-04-01             1.21
4  1970-05-01             1.21

# Step 2: Inspect Source 2 - UK Fuel Data

In [ ]:
import pandas as pd

# Load and inspect source2_uk.xlsx
df_raw2 = pd.read_excel("../data/raw/source2_uk.xlsx", sheet_name="4.1.1", header=None)
print("Source 2 UK - Shape:", df_raw2.shape)
print("Sample data:")
df_raw2.head(20)

Source 2 UK - Shape: (457, 15)
Sample data:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Table 4.1.1 Typical retail prices of petroleum...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Note 1. These estimates are representative of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note 2. Data for Premium Unleaded and Diesel a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Note 3. These estimates are for deliveries of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Note 4. Price index for supplies received by r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Blank cells in this table represent months whe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,An r indicates revised data. An r in the date ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Freeze panes are turned on. To turn off freeze...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Source: Department for Energy Security and Net...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Year,Month,Motor spirit:\n4 star / LRP\n(Pence per litre)...,Motor spirit: Super unleaded \n(Pence per litr...,Motor spirit: Premium unleaded / ULSP\n(Pence ...,Derv: Diesel / ULSD\n(Pence per litre)\n[Note ...,Standard grade burning oil\n(Pence per litre)\...,"Gas oil\n(Pence per litre)\n[Note 1, 3]",Crude oil acquired by refineries\n2025 = 100\n...,ULSP to ULSD Differential (Pence per litre),Historic Indices: Crude oil acquired by refine...,Historic Indices: Crude oil acquired by refine...,Historic Indices: Crude oil acquired by refine...,Historic Indices: Crude oil acquired by refine...,Month / Year
10,1989,January,37.14,NaN,36.02,34.17,11.41,11.15,NaN,NaN,NaN,NaN,NaN,NaN,1989-01-01 00:00:00
11,1989,February,38.3,NaN,36.88,35.03,10.83,10.49,NaN,NaN,NaN,NaN,NaN,NaN,1989-02-01 00:00:00
12,1989,March,38.85,NaN,37.3,35.09,11.4,10.9,NaN,NaN,NaN,NaN,NaN,NaN,1989-03-01 00:00:00
13,1989,April,41.14,NaN,39.09,36.08,11.45,10.83,NaN,NaN,NaN,NaN,NaN,NaN,1989-04-01 00:00:00
14,1989,May,42.83,NaN,40.81,36.06,11.41,10.81,NaN,NaN,NaN,NaN,NaN,NaN,1989-05-01 00:00:00
15,1989,June,42.7,NaN,40.74,35.93,11.48,11.26,NaN,NaN,NaN,NaN,NaN,NaN,1989-06-01 00:00:00
16,1989,July,41.49,NaN,39.26,35.87,11,10.91,NaN,NaN,NaN,NaN,NaN,NaN,1989-07-01 00:00:00
17,1989,August,39.92,NaN,37.4,35.7,11.48,11.19,NaN,NaN,NaN,NaN,NaN,NaN,1989-08-01 00:00:00
18,1989,September,40.79,NaN,38.19,36,12.33,11.89,NaN,NaN,NaN,NaN,NaN,NaN,1989-09-01 00:00:00
19,1989,October,40.89,NaN,38.3,37.33,13.13,12.5,NaN,NaN,NaN,NaN,NaN,NaN,1989-10-01 00:00:00

# Step 3: Inspect Source 3 - Additional UK Fuel Data

In [ ]:
import pandas as pd

# Check available sheets in source3_uk.xlsx
xls = pd.ExcelFile("../data/raw/source3_uk.xlsx")
print("Sheets in source3_uk.xlsx:", xls.sheet_names)

# Load and inspect the main data sheet
df_raw3 = pd.read_excel("../data/raw/source3_uk.xlsx", sheet_name="5.1.1 (excl tax)", header=None)
print("Source 3 UK - Shape:", df_raw3.shape)
print("Sample data:")
df_raw3.head(20)

Sheets in source3_uk.xlsx:

 ['Cover Sheet', 'Contents', '5.1.1 (excl tax)', '5.1.1 (incl tax)', '5.1.1 (tax amount)', '5.1.1 (% tax)', '5.2.1 (excl tax)', '5.2.1 (incl tax)', '5.2.1 (tax amount)', '5.2.1 (% tax)', 'Charts', 'Methodology', 'chart_data']
Source 3 UK - Shape: (334, 33)
Sample data:

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Table 5.1.1 Premium unleaded petrol prices exc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,In pence per litre and for premium unleaded pe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note 1. UK prices are sourced from a larger sa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Empty cells in the table represent periods whe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,An r indicates revised data. An r in the date ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Freeze panes are turned on. To turn off freeze...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Source: European Commission Oil Bulletin (non-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Year,Month,Day in month of price snapshot,Austria,Belgium,Denmark,Finland,France,Germany,Greece,...,Hungary,Latvia,Lithuania,Malta,Poland,Romania,Slovakia,Slovenia,UK Rank in EU14 plus UK,UK Rank in EU27 plus UK
8,1999,1999-01-01 00:00:00,NaN,16.081134,12.632888,13.414289,10.456732,10.406246,12.691287,12.766691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
9,1999,1999-02-01 00:00:00,NaN,15.743908,12.619214,13.414289,10.266548,10.196019,11.950962,13.005249,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
10,1999,1999-03-01 00:00:00,NaN,16.122724,13.311451,13.785362,13.583976,10.353689,12.761794,13.511111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
11,1999,1999-04-01 00:00:00,NaN,15.527544,14.900965,15.320655,14.125612,11.878762,14.643389,15.301578,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
12,1999,1999-05-01 00:00:00,NaN,16.161544,15.394735,15.825349,16.653905,12.428002,12.183886,15.674556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
13,1999,1999-06-01 00:00:00,NaN,16.041615,14.72547,15.825349,16.571971,12.110006,13.365149,15.200283,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
14,1999,1999-07-01 00:00:00,NaN,16.761185,16.320907,17.601483,17.276288,13.292428,15.727676,16.322362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
15,1999,1999-08-01 00:00:00,NaN,18.204163,19.978138,19.16448,18.128151,14.129682,17.145192,17.315408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
16,1999,1999-09-01 00:00:00,NaN,19.123294,17.463076,18.454027,20.293945,15.19839,17.853949,17.766921,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
17,1999,1999-10-01 00:00:00,NaN,19.842864,18.341793,17.885664,19.465841,15.716643,17.583946,18.41107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
18,1999,1999-11-01 00:00:00,NaN,18.765797,16.214977,17.801689,18.989571,15.229242,17.068989,17.139057,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
19,1999,1999-12-01 00:00:00,NaN,20.193222,19.361002,19.515037,19.455042,17.288298,18.36545,18.587999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

# Step 4: Trim to Relevant Rows and Save Clean CSVs

We have inspected the raw Excel files, and now we create cleaned CSV exports from the notebook itself:

- **Source 1**: already a CSV file, no trimming needed
- **Source 2**: use row 9 as header, row 10+ as data
- **Source 3**: use row 7 as header, row 8+ as data

This keeps `convert_files.py` simple and makes the row-selection logic explicit in the notebook.

In [ ]:
import os

processed_dir = "../data/processed"
os.makedirs(processed_dir, exist_ok=True)

# Source 2: extract header row and data rows after inspection
headers2 = df_raw2.iloc[9].fillna('').astype(str).tolist()
df2_clean = df_raw2.iloc[10:].reset_index(drop=True)
df2_clean.columns = headers2
df2_clean = df2_clean.dropna(how='all')
print('Source 2 cleaned shape:', df2_clean.shape)
print(df2_clean.head(5))

# Source 3: extract header row and data rows after inspection
headers3 = df_raw3.iloc[7].fillna('').astype(str).tolist()
df3_clean = df_raw3.iloc[8:].reset_index(drop=True)
df3_clean.columns = headers3
df3_clean = df3_clean.dropna(how='all')
print('Source 3 cleaned shape:', df3_clean.shape)
print(df3_clean.head(5))

# Save cleaned CSV files
source2_csv = os.path.join(processed_dir, 'source2_uk_clean.csv')
source3_csv = os.path.join(processed_dir, 'source3_uk_clean.csv')
df2_clean.to_csv(source2_csv, index=False)
df3_clean.to_csv(source3_csv, index=False)
print(f'Saved cleaned source2 CSV to: {source2_csv}')
print(f'Saved cleaned source3 CSV to: {source3_csv}')

# Verify output files
csv_files = [f for f in os.listdir(processed_dir) if f.endswith('.csv')]
print('Current processed CSV files:', csv_files)

Source 2 cleaned shape: (447, 15)
   Year     Month Motor spirit:\n4 star / LRP\n(Pence per litre)\n[Note 1]  \
0  1989   January                                              37.14
1  1989  February                                               38.3
2  1989     March                                              38.85
3  1989     April                                              41.14
4  1989       May                                              42.83

  Motor spirit: Super unleaded \n(Pence per litre)\n[Note 1]  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Motor spirit: Premium unleaded / ULSP\n(Pence per litre)\n[Note 1, 2]  \
0                                              36.02
1                                              36.88
2                                               37.3
3                                              39.09
4                                              40.81

  Derv: Diesel / ULSD\n(Pence per litre)\n[Note 1, 2]  \
0                                              34.17
1                                              35.03
2                                              35.09
3                                              36.08
4                                              36.06

  Standard grade burning oil\n(Pence per litre)\n[Note 1]  \
0                                              11.41
1                                              10.83
2                                               11.4
3                                              11.45
4                                              11.41

  Gas oil\n(Pence per litre)\n[Note 1, 3]  \
0                                   11.15
1                                   10.49
2                                    10.9
3                                   10.83
4                                   10.81

  Crude oil acquired by refineries\n2025 = 100\n[Note 4]  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  ULSP to ULSD Differential (Pence per litre)  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

  Historic Indices: Crude oil acquired by refineries\n2010 = 100  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Historic Indices: Crude oil acquired by refineries\n2005 = 100  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Historic Indices: Crude oil acquired by refineries\n2000 = 100  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Historic Indices: Crude oil acquired by refineries\n1995 = 100  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

          Month / Year
0  1989-01-01 00:00:00
1  1989-02-01 00:00:00
2  1989-03-01 00:00:00
3  1989-04-01 00:00:00
4  1989-05-01 00:00:00
Source 3 cleaned shape: (326, 33)
   Year                Month Day in month of price snapshot    Austria  \
0  1999  1999-01-01 00:00:00                            NaN  16.081134
1  1999  1999-02-01 00:00:00                            NaN  15.743908
2  1999  1999-03-01 00:00:00                            NaN  16.122724
3  1999  1999-04-01 00:00:00                            NaN  15.527544
4  1999  1999-05-01 00:00:00                            NaN  16.161544

     Belgium    Denmark    Finland     France    Germany     Greece  ...  \
0  12.632888  13.414289  10.456732  10.406246  12.691287  12.766691  ...
1  12.619214  13.414289  10.266548  10.196019  11.950962  13.005249  ...
2  13.311451  13.785362  13.583976  10.353689  12.761794  13.511111  ...
3  14.900965  15.320655  14.125612  11.878762  14.643389  15.301578  ...
4  15.394735  15.825349  16.653905  12.428002  12.183886  15.674556  ...

  Hungary Latvia Lithuania Malta Poland Romania Slovakia Slovenia  \
0     NaN    NaN       NaN   NaN    NaN     NaN      NaN      NaN
1     NaN    NaN       NaN   NaN    NaN     NaN      NaN      NaN
2     NaN    NaN       NaN   NaN    NaN     NaN      NaN      NaN
3     NaN    NaN       NaN   NaN    NaN     NaN      NaN      NaN
4     NaN    NaN       NaN   NaN    NaN     NaN      NaN      NaN

  UK Rank in EU14 plus UK UK Rank in EU27 plus UK
0                       1                     NaN
1                       1                     NaN
2                       1                     NaN
3                       2                     NaN
4                       2                     NaN

[5 rows x 33 columns]
Saved cleaned source2 CSV to: ../data/processed/source2_uk_clean.csv
Saved cleaned source3 CSV to: ../data/processed/source3_uk_clean.csv
Current processed CSV files: ['source2_uk_clean.csv', 'source3_uk_clean.csv']

# Step 5: Quick EDA on Processed CSV Files

Now that the CSV exports are created, we inspect the processed files to confirm what was captured.

In [ ]:
import pandas as pd

# Load cleaned processed files for quick EDA
processed_source2 = pd.read_csv(source2_csv)
processed_source3 = pd.read_csv(source3_csv)

print('Processed Source 2 shape:', processed_source2.shape)
print('Processed Source 2 columns:', processed_source2.columns.tolist())
print('Processed Source 2 head(10):')
print(processed_source2.head(10).to_string(index=False))

print('\nProcessed Source 3 shape:', processed_source3.shape)
print('Processed Source 3 columns:', processed_source3.columns.tolist())
print('Processed Source 3 head(10):')
print(processed_source3.head(10).to_string(index=False))

Processed Source 2 shape: (447, 15)
Processed Source 2 columns: ['Year', 'Month', 'Motor spirit:\n4 star / LRP\n(Pence per litre)\n[Note 1]', 'Motor spirit: Super unleaded \n(Pence per litre)\n[Note 1]', 'Motor spirit: Premium unleaded / ULSP\n(Pence per litre)\n[Note 1, 2]', 'Derv: Diesel / ULSD\n(Pence per litre)\n[Note 1, 2]', 'Standard grade burning oil\n(Pence per litre)\n[Note 1]', 'Gas oil\n(Pence per litre)\n[Note 1, 3]', 'Crude oil acquired by refineries\n2025 = 100\n[Note 4]', 'ULSP to ULSD Differential (Pence per litre)', 'Historic Indices: Crude oil acquired by refineries\n2010 = 100', 'Historic Indices: Crude oil acquired by refineries\n2005 = 100', 'Historic Indices: Crude oil acquired by refineries\n2000 = 100', 'Historic Indices: Crude oil acquired by refineries\n1995 = 100', 'Month / Year']
Processed Source 2 head(10):
 Year     Month  Motor spirit:\n4 star / LRP\n(Pence per litre)\n[Note 1]  Motor spirit: Super unleaded \n(Pence per litre)\n[Note 1]  Motor spirit: Premium unleaded / ULSP\n(Pence per litre)\n[Note 1, 2]  Derv: Diesel / ULSD\n(Pence per litre)\n[Note 1, 2]  Standard grade burning oil\n(Pence per litre)\n[Note 1]  Gas oil\n(Pence per litre)\n[Note 1, 3]  Crude oil acquired by refineries\n2025 = 100\n[Note 4]  ULSP to ULSD Differential (Pence per litre)  Historic Indices: Crude oil acquired by refineries\n2010 = 100  Historic Indices: Crude oil acquired by refineries\n2005 = 100  Historic Indices: Crude oil acquired by refineries\n2000 = 100 Historic Indices: Crude oil acquired by refineries\n1995 = 100        Month / Year
 1989   January                                                     37.14                                                         NaN                                                                  36.02                                                34.17                                                    11.41                                    11.15                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-01-01 00:00:00
 1989  February                                                     38.30                                                         NaN                                                                  36.88                                                35.03                                                    10.83                                    10.49                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-02-01 00:00:00
 1989     March                                                     38.85                                                         NaN                                                                  37.30                                                35.09                                                    11.40                                    10.90                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-03-01 00:00:00
 1989     April                                                     41.14                                                         NaN                                                                  39.09                                                36.08                                                    11.45                                    10.83                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-04-01 00:00:00
 1989       May                                                     42.83                                                         NaN                                                                  40.81                                                36.06                                                    11.41                                    10.81                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-05-01 00:00:00
 1989      June                                                     42.70                                                         NaN                                                                  40.74                                                35.93                                                    11.48                                    11.26                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-06-01 00:00:00
 1989      July                                                     41.49                                                         NaN                                                                  39.26                                                35.87                                                    11.00                                    10.91                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-07-01 00:00:00
 1989    August                                                     39.92                                                         NaN                                                                  37.40                                                35.70                                                    11.48                                    11.19                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-08-01 00:00:00
 1989 September                                                     40.79                                                         NaN                                                                  38.19                                                36.00                                                    12.33                                    11.89                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-09-01 00:00:00
 1989   October                                                     40.89                                                         NaN                                                                  38.30                                                37.33                                                    13.13                                    12.50                                                     NaN                                          NaN                                                             NaN                                                             NaN                                                             NaN                                                            NaN 1989-10-01 00:00:00

Processed Source 3 shape: (326, 33)
Processed Source 3 columns: ['Year', 'Month', 'Day in month of price snapshot', 'Austria', 'Belgium', 'Denmark', 'Finland', 'France', 'Germany', 'Greece', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Portugal', 'Spain', 'Sweden', 'United Kingdom [Note 1]', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Estonia', 'Hungary', 'Latvia', 'Lithuania', 'Malta', 'Poland', 'Romania', 'Slovakia', 'Slovenia', 'UK Rank in EU14 plus UK', 'UK Rank in EU27 plus UK']
Processed Source 3 head(10):
 Year               Month Day in month of price snapshot   Austria   Belgium   Denmark   Finland    France   Germany    Greece   Ireland     Italy  Luxembourg  Netherlands  Portugal     Spain    Sweden  United Kingdom [Note 1]  Bulgaria  Croatia  Cyprus  Czechia  Estonia  Hungary  Latvia  Lithuania  Malta  Poland  Romania  Slovakia  Slovenia  UK Rank in EU14 plus UK  UK Rank in EU27 plus UK
 1999 1999-01-01 00:00:00                            NaN 16.081134 12.632888 13.414289 10.456732 10.406246 12.691287 12.766691 14.913953 14.044111   13.143947    15.737937 13.518509 12.465087 13.745734                     9.51       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN
 1999 1999-02-01 00:00:00                            NaN 15.743908 12.619214 13.414289 10.266548 10.196019 11.950962 13.005249 14.262589 13.977414   13.143947    14.642852 12.933843 12.398369 14.056372                     9.65       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN
 1999 1999-03-01 00:00:00                            NaN 16.122724 13.311451 13.785362 13.583976 10.353689 12.761794 13.511111 13.972802 14.689608   13.878914    15.456344 12.933843 12.775057 14.553393                     9.39       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN
 1999 1999-04-01 00:00:00                            NaN 15.527544 14.900965 15.320655 14.125612 11.878762 14.643389 15.301578 13.624242 16.116874   15.615931    16.901235 13.181281 14.158682 16.054703                    12.53       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        2                      NaN
 1999 1999-05-01 00:00:00                            NaN 16.161544 15.394735 15.825349 16.653905 12.428002 12.183886 15.674556 14.416324 16.506233   16.199817    17.103752 14.094483 14.508346 16.360507                    12.40       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        2                      NaN
 1999 1999-06-01 00:00:00                            NaN 16.041615 14.725470 15.825349 16.571971 12.110006 13.365149 15.200283 15.593936 16.477937   15.758004    16.834166 14.785921 14.778915 16.301497                    12.20       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        2                      NaN
 1999 1999-07-01 00:00:00                            NaN 16.761185 16.320907 17.601483 17.276288 13.292428 15.727676 16.322362 15.940096 17.699429   16.936172    18.871040 15.016401 15.984175 17.481696                    13.19       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN
 1999 1999-08-01 00:00:00                            NaN 18.204163 19.978138 19.164480 18.128151 14.129682 17.145192 17.315408 16.355822 18.154207   18.392520    19.649845 16.695609 17.118420 18.425855                    14.81       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        2                      NaN
 1999 1999-09-01 00:00:00                            NaN 19.123294 17.463076 18.454027 20.293945 15.198390 17.853949 17.766921 17.671731 18.949558   18.392520    19.380259 18.341891 17.415966 18.720905                    14.94       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN
 1999 1999-10-01 00:00:00                            NaN 19.842864 18.341793 17.885664 19.465841 15.716643 17.583946 18.411070 18.849343 19.290471   18.687062    19.889477 18.308966 17.523876 19.842094                    15.64       NaN      NaN     NaN      NaN      NaN      NaN     NaN        NaN    NaN     NaN      NaN       NaN       NaN                        1                      NaN